---
- name: Configure home server
  hosts: home_servers
  become: true
  
  vars:
    # BaseOS configuration
    baseos_ssh_users:
      - name: admin
        password: "{{ vault_admin_password }}"
        ssh_key: "{{ vault_admin_ssh_key }}"
        sudo: true
        groups: ["sudo", "docker"]
      - name: user1
        password: "{{ vault_user1_password }}"
        ssh_key: "{{ vault_user1_ssh_key }}"
        sudo: false
    
    baseos_packages:
      - mc
      - atop
      - htop
      - vim
      - curl
      - wget
      - unzip
      - tree
      - git
      - docker.io
      - docker-compose
    
    baseos_ssh_config:
      permit_root_login: false
      password_authentication: false
      pubkey_authentication: true
      port: 22
    
    baseos_timezone: "Europe/Moscow"
    baseos_locale: "ru_RU.UTF-8"
    
    # PostgreSQL configuration
    postgresql_version: "17"
    
    # PostgreSQL data directories (optional)
    postgresql_data_directory: "/var/lib/postgresql/data"
    postgresql_wal_directory: "/var/lib/postgresql/wal"
    
    postgresql_users:
      - name: app_user
        password: "{{ vault_app_password }}"
        privileges: "ALL"
        role_attr_flags: "CREATEDB,NOSUPERUSER"
        databases: ["app_db"]
      - name: readonly_user
        password: "{{ vault_readonly_password }}"
        privileges: "SELECT"
        databases: ["app_db"]
    
    postgresql_databases:
      - name: app_db
        owner: app_user
        encoding: UTF8
        template: template0
        lc_collate: ru_RU.UTF-8
        lc_ctype: ru_RU.UTF-8
      - name: test_db
        owner: app_user
        encoding: UTF8
        template: template0
        lc_collate: ru_RU.UTF-8
        lc_ctype: ru_RU.UTF-8
    
    postgresql_extensions:
      - pg_stat_statements
      - uuid-ossp
      - hstore
    
    postgresql_backup:
      enabled: true
      path: "/var/backups/postgresql"
      retention_days: 7
      cron_schedule: "0 2 * * *"
    
    postgresql_config:
      listen_addresses: "*"
      port: 5432
      max_connections: 100
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "128MB"
      work_mem: "8MB"
  
  roles:
    - baseos
    - postgresql
