namespace: cheg
name: ansible_collection
version: 1.0.0
readme: README.md
authors:
  - CHeGIVaRO
description: Ansible Collection with roles for home using (PostgreSQL 17, base system configuration)
license:
  - MIT
tags:
  - system
  - database
  - home
repository: https://github.com/CHeGIVaRO/cheg-ansible-collection
documentation: https://github.com/CHeGIVaRO/cheg-ansible-collection
homepage: https://github.com/CHeGIVaRO/cheg-ansible-collection
issues: https://github.com/CHeGIVaRO/cheg-ansible-collection/issues
build_ignore: []
