---
- name: Configure SSH daemon
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    validate: 'sshd -t -f %s'
  become: true
  notify: restart ssh

- name: Ensure SSH service is enabled and running
  service:
    name: ssh
    state: started
    enabled: yes
  become: true
