---
- name: Create SSH users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    groups: "{{ item.groups | default([]) }}"
    append: yes
  become: true
  loop: "{{ baseos_ssh_users }}"
  when: item.password is defined

- name: Create SSH users with SSH keys
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
    groups: "{{ item.groups | default([]) }}"
    append: yes
  become: true
  loop: "{{ baseos_ssh_users }}"
  when: item.ssh_key is defined

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  become: true
  loop: "{{ baseos_ssh_users }}"
  when: item.ssh_key is defined

- name: Configure sudo access for users
  lineinfile:
    path: /etc/sudoers.d/{{ item.name }}
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    validate: 'visudo -cf %s'
  become: true
  loop: "{{ baseos_ssh_users }}"
  when: item.sudo | default(false)

- name: Create .ssh directory for users
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0700'
  become: true
  loop: "{{ baseos_ssh_users }}"
