---
galaxy_info:
  author: CHeGIVaRO
  description: Single-node PostgreSQL 17 installation and configuration role
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - database
    - postgresql
    - sql

dependencies: []
